### ISSUE TITLE
laravel 5.8 issue => Call to undefined method Rackbeat\BelongsToMorph::getOwnerKey() 

### ISSUE THREAD

**Issue by ibrahimabdallatif** [Rackbeat/laravel-morph-where-has#2]
I have used the package successfully with laravel 5.7 before, but with laravel 5.8 update the getOwnerKey() method name have been changed to getOwnerKeyName() in the class 'Illuminate\Database\Eloquent\Relations\BelongsTo'.

The package still uses the old method name when calling this method in 'Rackbeat\BelongsToMorph' Class .. line 138.

**Comment by LasseRafn** [comment]
Hi! We're still at 5.8 for a little while, but will update soon, and therefor this package will be fixed 👍 thanks for pointing this out

**Comment by LasseRafn** [comment]
Fixed in Release 1.1 👍
